"""estrutura inicial: empresa, usuario, categoria, fornecedor, produto, movimentacao

Revision ID: 1abc8de16adf
Revises: 
Create Date: 2026-08-14 22:01:21.315675

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1abc8de16adf'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('empresa',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=120), nullable=False),
    sa.Column('cnpj', sa.String(length=18), nullable=False),
    sa.Column('plano', sa.String(length=20), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_empresa')),
    sa.UniqueConstraint('cnpj', name=op.f('uq_empresa_cnpj'))
    )
    op.create_table('categoria',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=80), nullable=False),
    sa.Column('empresa_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresa.id'], name=op.f('fk_categoria_empresa_id_empresa')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_categoria')),
    sa.UniqueConstraint('nome', 'empresa_id', name=op.f('uq_categoria_nome_empresa_id'))
    )
    op.create_table('fornecedor',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=120), nullable=False),
    sa.Column('cnpj', sa.String(length=18), nullable=True),
    sa.Column('email', sa.String(length=180), nullable=True),
    sa.Column('telefone', sa.String(length=20), nullable=True),
    sa.Column('empresa_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresa.id'], name=op.f('fk_fornecedor_empresa_id_empresa')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_fornecedor')),
    sa.UniqueConstraint('cnpj', 'empresa_id', name=op.f('uq_fornecedor_cnpj_empresa_id'))
    )
    op.create_table('usuario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=180), nullable=False),
    sa.Column('senha_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('ADMIN', 'OPERADOR', name='role', native_enum=False), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('empresa_id', sa.Integer(), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("role IN ('ADMIN', 'OPERADOR')", name=op.f('ck_usuario_role')),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresa.id'], name=op.f('fk_usuario_empresa_id_empresa')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_usuario'))
    )
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_usuario_email'), ['email'], unique=True)

    op.create_table('produto',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sku', sa.String(length=40), nullable=False),
    sa.Column('nome', sa.String(length=160), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('categoria_id', sa.Integer(), nullable=False),
    sa.Column('fornecedor_id', sa.Integer(), nullable=True),
    sa.Column('preco_custo', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('preco_venda', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('estoque_minimo', sa.Integer(), nullable=False),
    sa.Column('unidade', sa.String(length=10), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('empresa_id', sa.Integer(), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('estoque_minimo >= 0', name=op.f('ck_produto_estoque_minimo_nao_negativo')),
    sa.CheckConstraint('preco_custo >= 0', name=op.f('ck_produto_preco_custo_nao_negativo')),
    sa.CheckConstraint('preco_venda >= 0', name=op.f('ck_produto_preco_venda_nao_negativo')),
    sa.ForeignKeyConstraint(['categoria_id'], ['categoria.id'], name=op.f('fk_produto_categoria_id_categoria')),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresa.id'], name=op.f('fk_produto_empresa_id_empresa')),
    sa.ForeignKeyConstraint(['fornecedor_id'], ['fornecedor.id'], name=op.f('fk_produto_fornecedor_id_fornecedor')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_produto')),
    sa.UniqueConstraint('sku', 'empresa_id', name=op.f('uq_produto_sku_empresa_id'))
    )
    with op.batch_alter_table('produto', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_produto_sku'), ['sku'], unique=False)

    op.create_table('movimentacao',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('produto_id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.Enum('ENTRADA', 'SAIDA', 'AJUSTE', name='tipo', native_enum=False), nullable=False),
    sa.Column('quantidade', sa.Integer(), nullable=False),
    sa.Column('custo_unitario', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('motivo', sa.String(length=255), nullable=True),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("tipo IN ('ENTRADA', 'SAIDA', 'AJUSTE')", name=op.f('ck_movimentacao_tipo')),
    sa.CheckConstraint('quantidade > 0', name=op.f('ck_movimentacao_quantidade_positiva')),
    sa.ForeignKeyConstraint(['produto_id'], ['produto.id'], name=op.f('fk_movimentacao_produto_id_produto')),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], name=op.f('fk_movimentacao_usuario_id_usuario')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_movimentacao'))
    )
    with op.batch_alter_table('movimentacao', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_movimentacao_criado_em'), ['criado_em'], unique=False)
        batch_op.create_index(batch_op.f('ix_movimentacao_produto_id'), ['produto_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('movimentacao', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_movimentacao_produto_id'))
        batch_op.drop_index(batch_op.f('ix_movimentacao_criado_em'))

    op.drop_table('movimentacao')
    with op.batch_alter_table('produto', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_produto_sku'))

    op.drop_table('produto')
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_usuario_email'))

    op.drop_table('usuario')
    op.drop_table('fornecedor')
    op.drop_table('categoria')
    op.drop_table('empresa')
    # ### end Alembic commands ###
